version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/output:/app/output
    restart: unless-stopped
    environment:
      - PORT=3001
      - NODE_ENV=production
